apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exercise.fullname" . }}-users-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "exercise.fullname" . }}-users-deployment
spec:
  replicas: {{ .Values.users.replicaCount }}
  strategy:
        type: RollingUpdate
  selector:
    matchLabels:
      app: {{ include "exercise.fullname" . }}-users-pod
  template:
    metadata:
      labels:
        app: {{ include "exercise.fullname" . }}-users-pod
    spec:
      containers:
      - name: users-container
        image: "{{ .Values.users.repository }}:{{ .Values.users.tag }}"
        imagePullPolicy: Always
        env:
        - name: ENV
          value: "{{ .Values.env }}"
        - name: SERVICE
          value: "users"
        ports:
        - containerPort: {{ .Values.users.containerPort }}
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
