# Default values for exercise.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
env: staging

namespace: staging

users:
  repository: pratikghodekar/exercise
  tag: latest
  replicaCount: 1
  service: users
  containerPort: 8080
  service:
    port: 80
    targetPort: 8080
    nodePort: 30165
  autoscaling:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

shifts:
  repository: pratikghodekar/exercise
  tag: latest
  replicaCount: 1
  service: users
  containerPort: 8080
  service:
    port: 80
    targetPort: 8080
    nodePort: 30166
  autoscaling:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
